### ISSUE TITLE
[BUG] Unable to configure bot in new guilds

### ISSUE THREAD

**Issue by alex4108** [alex4108/Approova#1]
:bug::scroll:

* **What is the current behavior?**

Bot won't respond to any configuration commands, *showConfig, *set(anything)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

```
Ignoring exception in command setApproverChannel:
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 85, in wrapped
 ret = await coro(*args, **kwargs)
 File "bot.py", line 233, in setApproverChannel
 if not is_owner(ctx.author):
 File "bot.py", line 71, in is_owner
 if member.id == member.guild.owner.id:
AttributeError: 'NoneType' object has no attribute 'id'
```

* **What is the expected behavior?**

Configuration should be able to be completed.

* **What is the motivation / use case for changing the behavior?**

Let the people use the app

* **Please tell us about your environment:** 
  
  - Are you using the code self-hosted, or are you using the public bot? Both
  - Please provide your Guild Name or Guild ID, along with any additional names or IDs to aide in log searching. Logs provided
 
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by alex4108** [comment]
#2 fixes this, waiting for confirmation, although it worked locally.
